[package]
name = "color-output"
version = "3.0.1"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = "An atomic output library based on Rust that supports output functionalities through functions, builders, and other methods. It allows customization of text and background colors."
keywords = ["output", "console", "log", "print", "color"]
repository = "https://github.com/ltpp-universe/color-output"
